sudo: required

services:
  - docker

before_install:
  - docker build -t amitkumar20491/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true amitkumar20491/client-test npm run test

after_success:
  - docker build -t amitkumar20491/fibcalc-client ./client
  - docker build -t amitkumar20491/fibcalc-nginx ./nginx
  - docker build -t amitkumar20491/fibcalc-server ./server
  - docker build -t amitkumar20491/fibcalc-worker ./worker
  #Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push amitkumar20491/fibcalc-client
  - docker push amitkumar20491/fibcalc-nginx
  - docker push amitkumar20491/fibcalc-server
  - docker push amitkumar20491/fibcalc-worker

