sudo: required

services:
  - docker

before_install:
  - docker build -t amitkumar20491/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true amitkumar20491/client-test npm run test

after_success:
  - docker build -t amitkumar20491/fibcalc-client ./client
  - docker build -t amitkumar20491/fibcalc-nginx ./nginx
  - docker build -t amitkumar20491/fibcalc-server ./server
  - docker build -t amitkumar20491/fibcalc-worker ./worker
  #Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push amitkumar20491/fibcalc-client
  - docker push amitkumar20491/fibcalc-nginx
  - docker push amitkumar20491/fibcalc-server
  - docker push amitkumar20491/fibcalc-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "fibonacci-calculator"
  env: "FibonacciCalculator-env"
  bucket_name: "elasticbeanstalk-us-east-1-631759633029"
  bucket_path: "fibonacci-calculator"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
